### PR TITLE
getLonLat

### PR DESCRIPTION
**Pull request by hewerthomn**

### CODE REVIEW

**Comment by lpolepeddi** [comment]
Thanks @hewerthomn! 

Is the site up online? I've tried to visit the URL https://getlonlat.hewertho.mn/ couple times and have been getting this error each time:

screen shot 2016-02-09 at 11 32 16 am

**Comment by hewerthomn** [comment]
Is online, but not on https, only http. http://getlonlat.hewertho.mn/

**Comment by lpolepeddi** [comment]
Great! getLonLat is up on Made with Angular https://www.madewithangular.com/#/sites/getlonlat

**Comment by hewerthomn** [comment]
Thanks! :D

**Pull request closed without merging**
