### PR TITLE
add Rhonexpress

### PR DESCRIPTION
**Pull request by manekinekko**
Suggesting Rhonexpress

### CODE REVIEW

**Comment by lpolepeddi** [comment]
Thanks @manekinekko! Rhonexpress is up on Made with Angular - https://www.madewithangular.com/#/sites/rhonexpress

**Comment by manekinekko** [comment]
Thanks @lpolepeddi

However, the app I submitted is not the website (http://rhonexpress.fr) but a mobile app made with angular, as you can see from the screenshot: 

AVRHEX

The image is in my PR ;)

Do you think you could fix that?

**Comment by lpolepeddi** [comment]
Sorry about that @manekinekko!

Made with Angular uses full screen screenshots for its thumbnails. For consistency, could you please choose one of the screens in your image and attach it? I'll update it on the site.

Thanks!

**Comment by manekinekko** [comment]
Thank you @lpolepeddi 

Is this screenshot OK?

image

**Comment by lpolepeddi** [comment]
Perfect, thanks @manekinekko! The image is updated on Made with Angular - https://www.madewithangular.com/#/sites/rhonexpress

**Comment by manekinekko** [comment]
Awesome :)

How to access the description field?

**Comment by lpolepeddi** [comment]
Currently not using the description field on the site, but may add it in a future iteration.

**Comment by manekinekko** [comment]
Oh I see. Ok ;)

**Pull request closed without merging**
