### PR TITLE
add dareboost.com project

### PR DESCRIPTION
**Pull request by DareBoost**

### CODE REVIEW

**Comment by lpolepeddi** [comment]
Hi @dareboost, thanks for the submission. I changed the design of the site and am using 1280x711 images now. I'm sorry the README wasn't updated with this info, I changed it now (https://github.com/madewithangular/madewithangular.github.io/commit/c0b4cb2713492687069dfbd82ef31f30f5b0958e). Could you send over a new screenshot that is 1280x711? Thanks!

**Comment by DareBoost** [comment]
Hi @lpolepeddi
ok! I'm taking care of that right now

**Comment by DareBoost** [comment]
done

**Comment by lpolepeddi** [comment]
Hi @DareBoost your project is [now up on the site](http://www.madewithangular.com/). I'll [tweet about it](https://twitter.com/madewithangular) in the coming weeks Thanks again!

**Pull request merged**
