### PR TITLE
Submitting electron insert factor modelling web app. Made with Angular2.

### PR DESCRIPTION
**Pull request by SimonBiggs**

### CODE REVIEW

**Comment by lpolepeddi** [comment]
@SimonBiggs thanks! Electron insert factor modeling is now up on Made with Angular - https://www.madewithangular.com/#/sites/electron-insert-factor-modelling

**Comment by SimonBiggs** [comment]
Thanks. Appreciate it.

**Comment by SimonBiggs** [comment]
By the way, the website front page on my mobile now appears broken. I hope that wasn't my doing...

**Comment by lpolepeddi** [comment]
Thanks for the heads up. Fixed the error, and the site's back up - https://www.madewithangular.com/#/

**Pull request closed without merging**
